### ISSUE TITLE
build fails with current beta dmd (Fedora 21, 64 bit)

### ISSUE THREAD

**Issue by Laeeth** [jacob-carlborg/dstep#33]
Any thoughts ?

tango.io.FileScan is deprecated. Please use tango.io.FilePath.toList or tango.io.vfs.* instead.
tango.math.BigInt is deprecated. Please use std.bigint instead.
../../../../root/.dub/packages/tango-1.0.0_2.066/tango/text/Regex.d(3781): Error: delegate dg (ref RegExpT!char) is not callable using argument types (RegExpT!char)
../../../../root/.dub/packages/tango-1.0.0_2.066/tango/text/Regex.d(4430): Error: template instance tango.text.Regex.RegExpT!char error instantiating
FAIL ../../../../root/.dub/packages/tango-1.0.0_2.066/.dub/build/static-debug-linux.posix-x86_64-dmd_2067-B138A764702A26D0FF777ECD4971FB9F/ tango staticLibrary
Error executing command run: dmd failed with exit code 1.

**Comment by jacob-carlborg** [comment]
> Any thoughts ?

No, not really. Looks like another regression in DMD. Would nice if you could report it in bugzilla.

**Comment by Laeeth** [comment]
The current version builds for you on regular dmd?  I am pretty sure it does not do so for me, but it was a few weeks ago that I checked.  What is your build environment?

**Comment by jacob-carlborg** [comment]
Yes, it builds with DMD 2.066.1, which is the latest version. I'm using OS X. It should build on Linux as well, since I fairly recently got a pull request https://github.com/jacob-carlborg/mambo/pull/3 to fix that :wink:

**Comment by jacob-carlborg** [comment]
I tried DMD 2.067.0-b1 and it doesn't compile. I filed a bug report: https://issues.dlang.org/show_bug.cgi?id=13934

**Comment by Dicebot** [comment]
It does not make much sense to put in effort into 2.067 beta as it has been abandoned ages ago and will likely be restarted from more recent master again once someone starts taking care of it again.

**Comment by Laeeth** [comment]
Thanks for coming back.

I downgraded my dmd as Dicebot suggested and am using a different machine now in case problem of local origin.  Trouble with clang build (error here, https://github.com/Andersbakken/rtags/issues/204 but the fix didn't work for me) so I used the Fedora 21 distributed clang.

I now have a problem at link stage with tango.

Target tango 1.0.0+2.066 is up to date. Use --force to rebuild.
Target mambo 0.0.3 is up to date. Use --force to rebuild.
Target dstack 0.0.2 is up to date. Use --force to rebuild.
Building dstep 0.1.1 configuration "application", build type debug.
Compiling using dmd...
Linking...
../../../root/.dub/packages/dstack-0.0.2/libdstack.a(Application_1_474.o): In function `_D5tango4text7convert6Layout13__T6LayoutTaZ6Layout6sprintMFAaAxaYAa':
/opt/git/dstep/../../../root/.dub/packages/tango-1.0.0_2.066/tango/text/convert/Layout.d:128: undefined reference to `_D4core4stdc6stdarg6va_endFNbPS4core4stdc6stdarg13__va_list_tagZv'
../../../root/.dub/packages/tango-1.0.0_2.066/libtango.a(Format_224_6b9.o): In function `_D5tango2io6stream6Format20__T12FormatOutputTaZ12FormatOutput6formatMFxAaYC5tango2io6stream6Format20__T12FormatOutputTaZ12FormatOutput':
/opt/git/dstep/../../../root/.dub/packages/tango-1.0.0_2.066/tango/io/stream/Format.d:157: undefined reference to `_D4core4stdc6stdarg6va_endFNbPS4core4stdc6stdarg13__va_list_tagZv'
../../../root/.dub/packages/tango-1.0.0_2.066/libtango.a(Format_224_6b9.o): In function `_D5tango2io6stream6Format20__T12FormatOutputTaZ12FormatOutput8formatlnMFxAaYC5tango2io6stream6Format20__T12FormatOutputTaZ12FormatOutput':
/opt/git/dstep/../../../root/.dub/packages/tango-1.0.0_2.066/tango/io/stream/Format.d:181: undefined reference to `_D4core4stdc6stdarg6va_endFNbPS4core4stdc6stdarg13__va_list_tagZv'
../../../root/.dub/packages/tango-1.0.0_2.066/libtango.a(Format_224_6b9.o): In function `_D5tango2io6stream6Format20__T12FormatOutputTaZ12FormatOutput5printMFYC5tango2io6stream6Format20__T12FormatOutputTaZ12FormatOutput':
/opt/git/dstep/../../../root/.dub/packages/tango-1.0.0_2.066/tango/io/stream/Format.d:217: undefined reference to `_D4core4stdc6stdarg6va_endFNbPS4core4stdc6stdarg13__va_list_tagZv'
../../../root/.dub/packages/tango-1.0.0_2.066/libtango.a(Format_224_6b9.o): In function `_D5tango4text7convert6Layout13__T6LayoutTaZ6Layout6sprintMFAaAxaYAa':
/opt/git/dstep/../../../root/.dub/packages/tango-1.0.0_2.066/tango/text/convert/Layout.d:128: undefined reference to `_D4core4stdc6stdarg6va_endFNbPS4core4stdc6stdarg13__va_list_tagZv'
../../../root/.dub/packages/tango-1.0.0_2.066/libtango.a(Format_224_6b9.o):/opt/git/dstep/../../../root/.dub/packages/tango-1.0.0_2.066/tango/text/convert/Layout.d:203: more undefined references to `_D4core4stdc6stdarg6va_endFNbPS4core4stdc6stdarg13__va_list_tagZv' follow
collect2: error: ld returned 1 exit status
--- errorlevel 1
FAIL .dub/build/application-debug-linux.posix-x86_64-dmd_2066-0E8A57E2F49ABF92B2E545BD241FBEE4/ dstep executable
Error executing command build: dmd failed with exit code 1.

**Comment by jacob-carlborg** [comment]
Hmm, I don't know. It seems to be some problem with a symbol in `core.stdc.stdarg`. BTW, can you use the pre-compiled binaries?

**Comment by jacob-carlborg** [comment]
@Laeeth BTW, it looks like you didin't use `--force` when building. It's always a good idea to use the flag when switching between different versions of the compiler. DMD does not have a stable ABI.

**Comment by Laeeth** [comment]
Hi.  I had tried using --force.  I am afraid I hadn't seen there were binaries available - my oversight.  Works fine for me, and I don't need to build from source now.  So I very much appreciate both your building this very useful tool, and your help recently.  Laeeth.

**Comment by jacob-carlborg** [comment]
Good, no worries :smiley:
