### ISSUE TITLE
Unable to compile with llvm 3.7

### ISSUE THREAD

**Issue by jelly** [jacob-carlborg/dstep#41]
I've tried to compile the master with 3.7 but it gives me the following compile error.

```dmd -O -m64 -L-ldl -m64  -c tango/math/Probability.d -ofobjs/tango/math/Probability.o
tango/math/IEEE.d(858): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!<='
dmd -O -m64 -L-ldl -m64  -c tango/math/random/ExpSource.d -ofobjs/tango/math/random/ExpSource.o
dmd -O -m64 -L-ldl -m64  -c tango/math/random/Kiss.d -ofobjs/tango/math/random/Kiss.o
dmd -O -m64 -L-ldl -m64  -c tango/math/random/NormalSource.d -ofobjs/tango/math/random/NormalSource.o
tango.math.BigInt is deprecated. Please use std.bigint instead.
tango/io/vfs/ZipFolder.d(302): Error: function tango.io.vfs.ZipFolder.ZipSubFolder.toString cannot have an in contract when overriden function object.Object.toString does not have an in contract
tango/io/vfs/ZipFolder.d(977): Error: function tango.io.vfs.ZipFolder.ZipFile.toString cannot have an in contract when overriden function object.Object.toString does not have an in contract
dmd -O -m64 -L-ldl -m64  -c tango/math/random/Random.d -ofobjs/tango/math/random/Random.o
dmd -O -m64 -L-ldl -m64  -c tango/math/random/Twister.d -ofobjs/tango/math/random/Twister.o
dmd -O -m64 -L-ldl -m64  -c tango/math/random/Ziggurat.d -ofobjs/tango/math/random/Ziggurat.o
build/Makefile:131: recipe for target 'objs/tango/io/vfs/ZipFolder.o' failed
make: *** [objs/tango/io/vfs/ZipFolder.o] Error 1
make: *** Waiting for unfinished jobs....
==> ERROR: A failure occurred in build().```

**Comment by jelly** [comment]
Nevermind, it's actually tango that does not compile

**Comment by jacob-carlborg** [comment]
If you're using DMD 2.068.0 you could try with these patches for Tango: https://github.com/SiegeLord/Tango-D2/pull/85

**Comment by jelly** [comment]
On 09/18/15 at 01:08pm, jacob-carlborg wrote:
> If you're using DMD 2.068.0 you could try with these patches for Tango: https://github.com/SiegeLord/Tango-D2/pull/85

Thanks, these patches make tango compile with llvm 3.7, just have two errors
left in mambo.

dstack/mambo/mambo/core/Array.d(23): Error: undefined identifier 'array'
in module 'std.algorithm'
dstack/mambo/mambo/core/Array.d(28): Error: undefined identifier 'join'
in module 'std.algorithm', did you mean template 'min(T...)(T args) if (T.length >= 2)'?

-- 
Jelle van der Waa

**Comment by jacob-carlborg** [comment]
> Thanks, these patches make tango compile with llvm 3.7, just have two errors left in mambo.

It compiles for me. Which version of the compiler are you using? Not sure what LLVM 3.7 has to do with this.

**Comment by Dicebot** [comment]
semi-OT: I have never been able to compile dstep + deps since build system changed to dub, neither with 2.066 nor 2.067 - always various compilation failures in tango. Don't have time to investigate for now thus temporary removing dstep package out of official Arch repos.

**Comment by jacob-carlborg** [comment]
@Dicebot that's weird. It compiles fine for me on OS X, Debian and on Travis CI [1].

[1] https://travis-ci.org/jacob-carlborg/dstep
